Repository Independent-Chain/inch-webapp, pull requests merged in 2024-10, with the labels that each got.

#74 [fix] Localization of upgrade confirmation
  Client/src/locales/en.json
  Client/src/locales/ru.json
  Client/src/pages/Upgrades/components/CellDevice/CellDevice.tsx
  Client/src/pages/Upgrades/helpers/formatUpgradeConfirm.ts
Labels: bug

#76 Fill the profile with information
  Client/src/api/api.rating.holders.js
  Client/src/api/api.rating.user.js
  Client/src/app/App.tsx
  Client/src/locales/en.json
  Client/src/locales/ru.json
  Client/src/modules/DailyReward/DailyReward.scss
  Client/src/modules/DailyReward/DailyReward.tsx
  Client/src/modules/Header/Header.scss
  Client/src/modules/NavigationPanel/NavigationPanel.scss
  Client/src/pages/Leaderboard/Leaderboard.scss
  Client/src/pages/Leaderboard/Leaderboard.tsx
  Client/src/pages/Leaderboard/components/UserRatingCard/UserRatingCard.scss
  Client/src/pages/Leaderboard/components/UserRatingCard/UserRatingCard.tsx
  Client/src/pages/Leaderboard/helpers/setMarker.js
  Client/src/pages/Leaderboard/modules/AllUsersRating/AllUsersRating.scss
  Client/src/pages/Leaderboard/modules/AllUsersRating/AllUsersRating.tsx
  Client/src/pages/Profile/Profile.scss
  Client/src/pages/Profile/Profile.tsx
  Client/src/pages/Profile/components/ProfileActionCell/ProfileActionCell.scss
  Client/src/pages/Profile/components/ProfileActionCell/ProfileActionCell.tsx
  Client/src/pages/Profile/modules/AboutUser/AboutUser.scss
  Client/src/pages/Profile/modules/AboutUser/AboutUser.tsx
  Client/src/pages/Profile/modules/ProfileCells/ProfileCells.scss
  Client/src/pages/Profile/modules/ProfileCells/ProfileCells.tsx
  Server/prisma/schema.prisma
  Server/src/app.module.ts
  Server/src/rating/rating.controller.ts
  Server/src/rating/rating.module.ts
  Server/src/rating/rating.service.ts
  Server/src/user/user.service.ts
Labels: feature

#78 Prepare app for release of new version
  Client/src/app/App.tsx
  Client/src/pages/Leaderboard/Leaderboard.tsx
  Client/src/pages/Tasks/Tasks.tsx
  Client/src/pages/Tasks/modules/TasksList/components/SingleTask/SingleTask.tsx
Labels: refactoring

#80 Upgrade translate feature
  Client/index.html
  Client/public/ui-icons/arrow-right-rounded.svg
  Client/public/ui-icons/en.svg
  Client/public/ui-icons/ru.svg
  Client/src/locales/en.json
  Client/src/locales/ru.json
  Client/src/modules/Header/Header.tsx
  Client/src/pages/Leaderboard/Leaderboard.tsx
  Client/src/pages/Profile/Profile.tsx
  Client/src/pages/Profile/components/TranslateCell/TranslateCell.scss
  Client/src/pages/Profile/components/TranslateCell/TranslateCell.tsx
  Client/src/pages/Profile/modules/AboutUser/AboutUser.scss
  Client/src/pages/Profile/modules/AboutUser/AboutUser.tsx
  Client/src/pages/Profile/modules/ProfileCells/ProfileCells.tsx
  Client/src/providers/LocalizationProvider.tsx
  Client/src/ui/Cell/Cell.tsx
Labels: upgrade
