Repository Independent-Chain/inch-webapp, pull requests merged in 2024-09, with the labels that each got.

#7 add debugging mode to run
  Client/src/app/App.tsx
  Client/src/components/Loading/Loading.tsx
  Client/src/context/AuthContext/AuthProvider.tsx
Labels: enhancement

#11 Redesign of device upgrade cards
  Client/public/locales/en.json
  Client/public/locales/ru.json
  Client/src/pages/Upgrades/Upgrades.tsx
  Client/src/pages/Upgrades/components/CellDevice/CellDevice.scss
  Client/src/pages/Upgrades/components/CellDevice/CellDevice.tsx
Labels: enhancement

#13 Prohibiting the use of landscape orientation
  Client/src/main.scss
Labels: enhancement

#14 Add check debug token ins start_param for launch debugging mode
  Client/src/app/App.tsx
Labels: upgrade

#23 fix start_param check
  Server/src/user/user.service.ts
Labels: bug

#24 revert fix start_param check
  Server/src/user/user.service.ts
Labels: bug

#25 create step-by-step for first launch of app
  Client/index.html
  Client/public/steps/step0.png
  Client/public/steps/step1.png
  Client/public/steps/step2.png
  Client/public/steps/step3.png
  Client/public/steps/step4.png
  Client/src/app/App.tsx
  Client/src/modules/StepByStep/StepByStep.scss
  Client/src/modules/StepByStep/StepByStep.tsx
Labels: enhancement

#27 refactoring App.tsx
  Client/src/app/App.tsx
Labels: refactoring

#28 locals refractoring
  Client/public/locales/en.json
  Client/public/locales/ru.json
  Client/src/context/LocaleContext/LocalizationProvider.tsx
  Client/src/locales/en.json
  Client/src/locales/ru.json
  Client/src/modules/NavigationPanel/NavigationPanel.tsx
Labels: refactoring

#43 Add RU and EN localization to the invitation
  Client/src/locales/en.json
  Client/src/locales/ru.json
  Client/src/pages/Profile/Profile.tsx
Labels: help wanted, upgrade

#42 Tasks mechanics
  Client/index.html
  Client/public/tasks-icons/telegram.svg
  Client/src/api/api.complete-task.js
  Client/src/api/api.get-tasks.js
  Client/src/context/AuthContext/AuthProvider.tsx
  Client/src/icons/IconTelegram.tsx
  Client/src/locales/en.json
  Client/src/locales/ru.json
  Client/src/pages/Tasks/Tasks.scss
  Client/src/pages/Tasks/Tasks.tsx
  Client/src/pages/Tasks/components/SingleTask/SingleTask.scss
  Client/src/pages/Tasks/components/SingleTask/SingleTask.tsx
  Client/src/pages/Tasks/modules/TasksList/TasksList.scss
  Client/src/pages/Tasks/modules/TasksList/TasksList.tsx
  Server/prisma/schema.prisma
  Server/src/app.module.ts
  Server/src/main.ts
  Server/src/tasks/dto/dto.completedTaskDatDto.ts
  Server/src/tasks/interfaces/i.completedTaskData.ts
  Server/src/tasks/tasks.controller.ts
  Server/src/tasks/tasks.module.ts
  Server/src/tasks/tasks.service.ts
  Server/src/user/user.controller.ts
  Server/src/user/user.service.ts
Labels: enhancement

#44 UI fix
  Client/index.html
  Client/public/coin.png
  Client/src/locales/en.json
  Client/src/locales/ru.json
  Client/src/pages/Home/modules/HomeCells/HomeCells.tsx
  Client/src/pages/Tasks/components/SingleTask/SingleTask.scss
  Client/src/pages/Tasks/components/SingleTask/SingleTask.tsx
  Client/src/ui/Cell/Cell.scss
  Client/src/ui/Cell/Cell.tsx
Labels: upgrade

#45 add signature verification
  Client/src/api/api.config.js
  Client/src/api/api.create-token.js
  Client/src/app/App.tsx
  Client/src/context/AuthContext/AuthProvider.tsx
  Server/package-lock.json
  Server/package.json
  Server/src/auth/auth.controller.ts
  Server/src/auth/auth.service.ts
  Server/src/main.ts
Labels: upgrade

#55 feature/debug-mode
  Client/src/api/api.auth.token.js
  Client/src/api/api.config.js
  Client/src/api/api.mining.claim.js
  Client/src/api/api.mining.upgrade.js
  Client/src/api/api.tasks.all.js
  Client/src/api/api.tasks.complete.js
  Client/src/api/api.user.create.js
  Client/src/api/api.user.get.js
  Client/src/api/api.user.locale.js
  Client/src/app/App.tsx
  Client/src/app/helpers/configAppMode.js
  Client/src/app/helpers/detectDevice.js
  Client/src/context/NotificationContext/NotificationProvider.tsx
  Client/src/ui/Notification/Notification.scss
  Client/src/ui/Notification/Notification.tsx
Labels: upgrade

#56 fix negative value of loot
  Client/src/pages/Home/helpers/calculateLoot.ts
Labels: bug

#57 Daily-rewards
  Client/index.html
  Client/public/coin.webp
  Client/src/api/api.daily.check.js
  Client/src/api/api.daily.take.js
  Client/src/app/App.tsx
  Client/src/locales/en.json
  Client/src/locales/ru.json
  Client/src/modules/DailyReward/DailyReward.scss
  Client/src/modules/DailyReward/DailyReward.tsx
  Server/prisma/schema.prisma
  Server/src/app.module.ts
  Server/src/daily/daily.controller.ts
  Server/src/daily/daily.module.ts
  Server/src/daily/daily.service.ts
  Server/src/main.ts
  Server/src/utils/configureDatabase.ts
Labels: enhancement
